# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fafef63b48f818543b4593df6a7306b43d424cf98f33de55c45d66d28c713cf9be27225c8ec7b3bbf71afbc07d01a7768fde97a68ecfe0e988db7df7d4119f

test:
  secret_key_base: 096f568754b873d72099cb42a97667227531a0e2a77cf98ef498e316e0edfaff8217b6fb05630f9b94b1796f92839239c53c65d3c2746c68f731e193069975cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
